// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2EUpYxz_pdb39cDmRm1tnId5iVtEgAE',
    appId: '1:711087751581:web:3843b57bdfaa9b2bb2ef74',
    messagingSenderId: '711087751581',
    projectId: 'chat-app-5adfa',
    authDomain: 'chat-app-5adfa.firebaseapp.com',
    storageBucket: 'chat-app-5adfa.appspot.com',
    measurementId: 'G-Z6HM7V38V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-1nfnX6l9Jd1FMjAm88Tkp9LT2gqRYqE',
    appId: '1:711087751581:android:8076bdb78cf8288fb2ef74',
    messagingSenderId: '711087751581',
    projectId: 'chat-app-5adfa',
    storageBucket: 'chat-app-5adfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQz7EgX0zfauiD0CySTxkhv0kILboaHqY',
    appId: '1:711087751581:ios:559e82d10079fbf4b2ef74',
    messagingSenderId: '711087751581',
    projectId: 'chat-app-5adfa',
    storageBucket: 'chat-app-5adfa.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQz7EgX0zfauiD0CySTxkhv0kILboaHqY',
    appId: '1:711087751581:ios:45203d7e9d76d35bb2ef74',
    messagingSenderId: '711087751581',
    projectId: 'chat-app-5adfa',
    storageBucket: 'chat-app-5adfa.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
